/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as JoinCodeRouteImport } from './routes/join_.$code'
import { Route as LeaguesIndexRouteImport } from './routes/leagues.index'
import { Route as LeaguesSlugRouteImport } from './routes/leagues.$slug'
import { Route as LeaguesNewRouteImport } from './routes/leagues.new'
import { Route as LeaguesSlugIndexRouteImport } from './routes/leagues.$slug.index'
import { Route as LeaguesSlugBracketRouteImport } from './routes/leagues.$slug.bracket'
import { Route as LeaguesSlugDraftRouteImport } from './routes/leagues.$slug.draft'
import { Route as LeaguesSlugPointsRouteImport } from './routes/leagues.$slug.points'
import { Route as LeaguesSlugPoolRouteImport } from './routes/leagues.$slug.pool'
import { Route as LeaguesSlugScheduleRouteImport } from './routes/leagues.$slug.schedule'
import { Route as LeaguesSlugSpeedRouteImport } from './routes/leagues.$slug.speed'
import { Route as LeaguesSlugStandingsRouteImport } from './routes/leagues.$slug.standings'
import { Route as LeaguesSlugTradesRouteImport } from './routes/leagues.$slug.trades'
import { Route as LeaguesSlugTeamsIndexRouteImport } from './routes/leagues.$slug.teams.index'
import { Route as LeaguesSlugTeamsMemberIdRouteImport } from './routes/leagues.$slug.teams.$memberId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join_/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesIndexRoute = LeaguesIndexRouteImport.update({
  id: '/leagues/',
  path: '/leagues/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugRoute = LeaguesSlugRouteImport.update({
  id: '/leagues/$slug',
  path: '/leagues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesNewRoute = LeaguesNewRouteImport.update({
  id: '/leagues/new',
  path: '/leagues/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaguesSlugIndexRoute = LeaguesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugBracketRoute = LeaguesSlugBracketRouteImport.update({
  id: '/bracket',
  path: '/bracket',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugDraftRoute = LeaguesSlugDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugPointsRoute = LeaguesSlugPointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugPoolRoute = LeaguesSlugPoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugScheduleRoute = LeaguesSlugScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugSpeedRoute = LeaguesSlugSpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugStandingsRoute = LeaguesSlugStandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugTradesRoute = LeaguesSlugTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugTeamsIndexRoute = LeaguesSlugTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => LeaguesSlugRoute,
} as any)
const LeaguesSlugTeamsMemberIdRoute =
  LeaguesSlugTeamsMemberIdRouteImport.update({
    id: '/teams/$memberId',
    path: '/teams/$memberId',
    getParentRoute: () => LeaguesSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/$slug': typeof LeaguesSlugRouteWithChildren
  '/leagues/new': typeof LeaguesNewRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/leagues/$slug/bracket': typeof LeaguesSlugBracketRoute
  '/leagues/$slug/draft': typeof LeaguesSlugDraftRoute
  '/leagues/$slug/points': typeof LeaguesSlugPointsRoute
  '/leagues/$slug/pool': typeof LeaguesSlugPoolRoute
  '/leagues/$slug/schedule': typeof LeaguesSlugScheduleRoute
  '/leagues/$slug/speed': typeof LeaguesSlugSpeedRoute
  '/leagues/$slug/standings': typeof LeaguesSlugStandingsRoute
  '/leagues/$slug/trades': typeof LeaguesSlugTradesRoute
  '/leagues/$slug/': typeof LeaguesSlugIndexRoute
  '/leagues/$slug/teams/$memberId': typeof LeaguesSlugTeamsMemberIdRoute
  '/leagues/$slug/teams/': typeof LeaguesSlugTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/join/$code': typeof JoinCodeRoute
  '/leagues/new': typeof LeaguesNewRoute
  '/leagues': typeof LeaguesIndexRoute
  '/leagues/$slug/bracket': typeof LeaguesSlugBracketRoute
  '/leagues/$slug/draft': typeof LeaguesSlugDraftRoute
  '/leagues/$slug/points': typeof LeaguesSlugPointsRoute
  '/leagues/$slug/pool': typeof LeaguesSlugPoolRoute
  '/leagues/$slug/schedule': typeof LeaguesSlugScheduleRoute
  '/leagues/$slug/speed': typeof LeaguesSlugSpeedRoute
  '/leagues/$slug/standings': typeof LeaguesSlugStandingsRoute
  '/leagues/$slug/trades': typeof LeaguesSlugTradesRoute
  '/leagues/$slug': typeof LeaguesSlugIndexRoute
  '/leagues/$slug/teams/$memberId': typeof LeaguesSlugTeamsMemberIdRoute
  '/leagues/$slug/teams': typeof LeaguesSlugTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/join_/$code': typeof JoinCodeRoute
  '/leagues/$slug': typeof LeaguesSlugRouteWithChildren
  '/leagues/new': typeof LeaguesNewRoute
  '/leagues/': typeof LeaguesIndexRoute
  '/leagues/$slug/bracket': typeof LeaguesSlugBracketRoute
  '/leagues/$slug/draft': typeof LeaguesSlugDraftRoute
  '/leagues/$slug/points': typeof LeaguesSlugPointsRoute
  '/leagues/$slug/pool': typeof LeaguesSlugPoolRoute
  '/leagues/$slug/schedule': typeof LeaguesSlugScheduleRoute
  '/leagues/$slug/speed': typeof LeaguesSlugSpeedRoute
  '/leagues/$slug/standings': typeof LeaguesSlugStandingsRoute
  '/leagues/$slug/trades': typeof LeaguesSlugTradesRoute
  '/leagues/$slug/': typeof LeaguesSlugIndexRoute
  '/leagues/$slug/teams/$memberId': typeof LeaguesSlugTeamsMemberIdRoute
  '/leagues/$slug/teams/': typeof LeaguesSlugTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/signup'
    | '/join/$code'
    | '/leagues/$slug'
    | '/leagues/new'
    | '/leagues/'
    | '/leagues/$slug/bracket'
    | '/leagues/$slug/draft'
    | '/leagues/$slug/points'
    | '/leagues/$slug/pool'
    | '/leagues/$slug/schedule'
    | '/leagues/$slug/speed'
    | '/leagues/$slug/standings'
    | '/leagues/$slug/trades'
    | '/leagues/$slug/'
    | '/leagues/$slug/teams/$memberId'
    | '/leagues/$slug/teams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/signup'
    | '/join/$code'
    | '/leagues/new'
    | '/leagues'
    | '/leagues/$slug/bracket'
    | '/leagues/$slug/draft'
    | '/leagues/$slug/points'
    | '/leagues/$slug/pool'
    | '/leagues/$slug/schedule'
    | '/leagues/$slug/speed'
    | '/leagues/$slug/standings'
    | '/leagues/$slug/trades'
    | '/leagues/$slug'
    | '/leagues/$slug/teams/$memberId'
    | '/leagues/$slug/teams'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/signup'
    | '/join_/$code'
    | '/leagues/$slug'
    | '/leagues/new'
    | '/leagues/'
    | '/leagues/$slug/bracket'
    | '/leagues/$slug/draft'
    | '/leagues/$slug/points'
    | '/leagues/$slug/pool'
    | '/leagues/$slug/schedule'
    | '/leagues/$slug/speed'
    | '/leagues/$slug/standings'
    | '/leagues/$slug/trades'
    | '/leagues/$slug/'
    | '/leagues/$slug/teams/$memberId'
    | '/leagues/$slug/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  JoinCodeRoute: typeof JoinCodeRoute
  LeaguesSlugRoute: typeof LeaguesSlugRouteWithChildren
  LeaguesNewRoute: typeof LeaguesNewRoute
  LeaguesIndexRoute: typeof LeaguesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join_/$code': {
      id: '/join_/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/': {
      id: '/leagues/'
      path: '/leagues'
      fullPath: '/leagues/'
      preLoaderRoute: typeof LeaguesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug': {
      id: '/leagues/$slug'
      path: '/leagues/$slug'
      fullPath: '/leagues/$slug'
      preLoaderRoute: typeof LeaguesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/new': {
      id: '/leagues/new'
      path: '/leagues/new'
      fullPath: '/leagues/new'
      preLoaderRoute: typeof LeaguesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leagues/$slug/': {
      id: '/leagues/$slug/'
      path: '/'
      fullPath: '/leagues/$slug/'
      preLoaderRoute: typeof LeaguesSlugIndexRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/bracket': {
      id: '/leagues/$slug/bracket'
      path: '/bracket'
      fullPath: '/leagues/$slug/bracket'
      preLoaderRoute: typeof LeaguesSlugBracketRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/draft': {
      id: '/leagues/$slug/draft'
      path: '/draft'
      fullPath: '/leagues/$slug/draft'
      preLoaderRoute: typeof LeaguesSlugDraftRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/points': {
      id: '/leagues/$slug/points'
      path: '/points'
      fullPath: '/leagues/$slug/points'
      preLoaderRoute: typeof LeaguesSlugPointsRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/pool': {
      id: '/leagues/$slug/pool'
      path: '/pool'
      fullPath: '/leagues/$slug/pool'
      preLoaderRoute: typeof LeaguesSlugPoolRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/schedule': {
      id: '/leagues/$slug/schedule'
      path: '/schedule'
      fullPath: '/leagues/$slug/schedule'
      preLoaderRoute: typeof LeaguesSlugScheduleRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/speed': {
      id: '/leagues/$slug/speed'
      path: '/speed'
      fullPath: '/leagues/$slug/speed'
      preLoaderRoute: typeof LeaguesSlugSpeedRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/standings': {
      id: '/leagues/$slug/standings'
      path: '/standings'
      fullPath: '/leagues/$slug/standings'
      preLoaderRoute: typeof LeaguesSlugStandingsRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/trades': {
      id: '/leagues/$slug/trades'
      path: '/trades'
      fullPath: '/leagues/$slug/trades'
      preLoaderRoute: typeof LeaguesSlugTradesRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/teams/': {
      id: '/leagues/$slug/teams/'
      path: '/teams'
      fullPath: '/leagues/$slug/teams/'
      preLoaderRoute: typeof LeaguesSlugTeamsIndexRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
    '/leagues/$slug/teams/$memberId': {
      id: '/leagues/$slug/teams/$memberId'
      path: '/teams/$memberId'
      fullPath: '/leagues/$slug/teams/$memberId'
      preLoaderRoute: typeof LeaguesSlugTeamsMemberIdRouteImport
      parentRoute: typeof LeaguesSlugRoute
    }
  }
}

interface LeaguesSlugRouteChildren {
  LeaguesSlugBracketRoute: typeof LeaguesSlugBracketRoute
  LeaguesSlugDraftRoute: typeof LeaguesSlugDraftRoute
  LeaguesSlugPointsRoute: typeof LeaguesSlugPointsRoute
  LeaguesSlugPoolRoute: typeof LeaguesSlugPoolRoute
  LeaguesSlugScheduleRoute: typeof LeaguesSlugScheduleRoute
  LeaguesSlugSpeedRoute: typeof LeaguesSlugSpeedRoute
  LeaguesSlugStandingsRoute: typeof LeaguesSlugStandingsRoute
  LeaguesSlugTradesRoute: typeof LeaguesSlugTradesRoute
  LeaguesSlugIndexRoute: typeof LeaguesSlugIndexRoute
  LeaguesSlugTeamsMemberIdRoute: typeof LeaguesSlugTeamsMemberIdRoute
  LeaguesSlugTeamsIndexRoute: typeof LeaguesSlugTeamsIndexRoute
}

const LeaguesSlugRouteChildren: LeaguesSlugRouteChildren = {
  LeaguesSlugBracketRoute: LeaguesSlugBracketRoute,
  LeaguesSlugDraftRoute: LeaguesSlugDraftRoute,
  LeaguesSlugPointsRoute: LeaguesSlugPointsRoute,
  LeaguesSlugPoolRoute: LeaguesSlugPoolRoute,
  LeaguesSlugScheduleRoute: LeaguesSlugScheduleRoute,
  LeaguesSlugSpeedRoute: LeaguesSlugSpeedRoute,
  LeaguesSlugStandingsRoute: LeaguesSlugStandingsRoute,
  LeaguesSlugTradesRoute: LeaguesSlugTradesRoute,
  LeaguesSlugIndexRoute: LeaguesSlugIndexRoute,
  LeaguesSlugTeamsMemberIdRoute: LeaguesSlugTeamsMemberIdRoute,
  LeaguesSlugTeamsIndexRoute: LeaguesSlugTeamsIndexRoute,
}

const LeaguesSlugRouteWithChildren = LeaguesSlugRoute._addFileChildren(
  LeaguesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  JoinCodeRoute: JoinCodeRoute,
  LeaguesSlugRoute: LeaguesSlugRouteWithChildren,
  LeaguesNewRoute: LeaguesNewRoute,
  LeaguesIndexRoute: LeaguesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
