/**
 * The client contract. Clients switch on `code`, never on message text, so
 * these strings are frozen once shipped — add new ones, never rename.
 */
export const ERROR_CODES = {
  // generic
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // leagues
  LEAGUE_NOT_FOUND: 'LEAGUE_NOT_FOUND',
  LEAGUE_FULL: 'LEAGUE_FULL',
  LEAGUE_INVALID_STATUS: 'LEAGUE_INVALID_STATUS',
  NOT_LEAGUE_MEMBER: 'NOT_LEAGUE_MEMBER',
  NOT_LEAGUE_HOST: 'NOT_LEAGUE_HOST',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  SLUG_TAKEN: 'SLUG_TAKEN',
  INVITE_INVALID: 'INVITE_INVALID',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_EXHAUSTED: 'INVITE_EXHAUSTED',
  CANNOT_REMOVE_HOST: 'CANNOT_REMOVE_HOST',

  // dex
  SPECIES_NOT_FOUND: 'SPECIES_NOT_FOUND',
  FORMAT_NOT_FOUND: 'FORMAT_NOT_FOUND',
  MOVE_NOT_FOUND: 'MOVE_NOT_FOUND',
  ABILITY_NOT_FOUND: 'ABILITY_NOT_FOUND',

  // points
  POINTS_PARSE_ERROR: 'POINTS_PARSE_ERROR',
  POINTS_TOO_LARGE: 'POINTS_TOO_LARGE',
  POINTS_LIST_NOT_FOUND: 'POINTS_LIST_NOT_FOUND',
  PREVIEW_STALE: 'PREVIEW_STALE',

  // draft
  DRAFT_NOT_FOUND: 'DRAFT_NOT_FOUND',
  DRAFT_NOT_ACTIVE: 'DRAFT_NOT_ACTIVE',
  DRAFT_ALREADY_STARTED: 'DRAFT_ALREADY_STARTED',
  DRAFT_PAUSED: 'DRAFT_PAUSED',
  NOT_YOUR_TURN: 'NOT_YOUR_TURN',
  SPECIES_ALREADY_PICKED: 'SPECIES_ALREADY_PICKED',
  SPECIES_NOT_IN_POOL: 'SPECIES_NOT_IN_POOL',
  SPECIES_ILLEGAL: 'SPECIES_ILLEGAL',
  SPECIES_BANNED: 'SPECIES_BANNED',
  INSUFFICIENT_POINTS: 'INSUFFICIENT_POINTS',
  ROSTER_FULL: 'ROSTER_FULL',
  ROSTER_UNREACHABLE: 'ROSTER_UNREACHABLE',
  NOTHING_TO_UNDO: 'NOTHING_TO_UNDO',

  // season
  SEASON_NOT_FOUND: 'SEASON_NOT_FOUND',
  SEASON_EXISTS: 'SEASON_EXISTS',
  MATCHUP_NOT_FOUND: 'MATCHUP_NOT_FOUND',
  NOT_MATCH_PARTICIPANT: 'NOT_MATCH_PARTICIPANT',
  REPORT_EXISTS: 'REPORT_EXISTS',
  REPORT_NOT_FOUND: 'REPORT_NOT_FOUND',
  INVALID_REPLAY_URL: 'INVALID_REPLAY_URL',

  // playoffs
  BRACKET_NOT_FOUND: 'BRACKET_NOT_FOUND',
  BRACKET_EXISTS: 'BRACKET_EXISTS',
  BRACKET_MATCH_NOT_READY: 'BRACKET_MATCH_NOT_READY',
  NOT_ENOUGH_TEAMS: 'NOT_ENOUGH_TEAMS',

  // transactions
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRADE_INVALID: 'TRADE_INVALID',
  TRADE_NOT_PENDING: 'TRADE_NOT_PENDING',
  NOT_TRADE_PARTICIPANT: 'NOT_TRADE_PARTICIPANT',
  TRADES_CLOSED: 'TRADES_CLOSED',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
